name: Publish results as github pages

on:
  push:
    branches:
      - main
  workflow_dispatch:
    

jobs:

  publish:
    permissions:
      contents: write
      pages: write
      id-token: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up asv 
        run: |
          pip install asv
          asv publish --config asv.conf.json 

      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: .asv/html
          destination: ./_site

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
      
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2